[build]
command = "npm run build"
publish = ".next"

# Build-only, not injected into Functions runtime
[build.environment]
# GA4
GA4_MEASUREMENT_ID = "G-RNFQXLZ6DD"

# App URLs
PORTAL_BASE_URL = "https://portal.theclearpath.ae"
NODE_VERSION = "20"

# If your build needs Firebase public vars, add them here exactly as used in your app:
# NEXT_PUBLIC_FIREBASE_API_KEY = "paste-real"
# NEXT_PUBLIC_FIREBASE_APP_ID = "paste-real"
# NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "theclearpath-6864e.firebaseapp.com"
# NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "paste-real"
# NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "paste-real"
# NEXT_PUBLIC_FIREBASE_PROJECT_ID = "theclearpath-6864e"
# NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "theclearpath-6864e.appspot.com"
